repos:
-   repo: https://github.com/psf/black
    rev: 23.12.1  # Use the latest version
    hooks:
    -   id: black
        language_version: python3.12
-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0  # Use the latest version
    hooks:
    -   id: flake8 